version: '3.1'
services:
  web:
    image: odoo-test:1
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    environment:
    - HOST=db
    - USER=odoo
    - PASSWORD=odoo
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata